- packages/models/migrations/1716146586880_setup.js
- packages/models/src/tutors.ts
- packages/models/src/users.ts
- packages/models/tests/users.test.ts
- packages/types/src/user.ts
- services/server/src/handlers/user.ts
Also Created Tests
modified update handlers to include city and phoneNumber, Also query handlers to include City
> feat(server): added phone number and city to user tables

- packages/auth/src/authorization.ts
- packages/auth/src/index.ts
- services/server/fixtures/api.ts
- services/server/fixtures/db.ts
- services/server/package.json
- services/server/src/handlers/auth.ts
- services/server/src/handlers/rating.ts
- services/server/src/handlers/user.ts
- services/server/tests/api/user.test.ts
This route `/list` always returns null, I didn't understand why :"""
@neuodev
> feat(server): added tests to user handler

- services/server/fixtures/wss.ts
- services/server/src/constants.ts
- services/server/tests/wss/messages.test.ts
Despite the name of the branch, two tasks appertain to messages are included in this branch: deleting messages and marking messages as read.
> added(wss server): unit tests for delete message wss handler function.

- packages/atlas/src/user.ts
- packages/headless/src/student.ts
- packages/types/src/tutor.ts
- packages/types/src/user.ts
- services/server/fixtures/api.ts
- services/server/src/handlers/user.ts
- services/server/src/routes/user.ts
- services/server/tests/api/user.test.ts
ClickUp Task: [https://app.clickup.com/t/86976y333](https://app.clickup.com/t/86976y333)
> added(server): find personalized tutor stats endpoint.

- apps/nova/src/lib/room.ts
- packages/types/src/room.ts
- services/server/src/handlers/chat.ts
- services/server/src/lib/chat.ts
- services/server/tests/api/chat.test.ts
ClickUp Task: [https://app.clickup.com/t/86976yw1c](https://app.clickup.com/t/86976yw1c)
> added(server): other member online status attr in the response of findUserRooms api handle.

- packages/atlas/src/user.ts
- packages/models/src/tutors.ts
- packages/models/tests/tutors.test.ts
- packages/types/src/tutor.ts
- services/server/src/handlers/user.ts
- services/server/src/routes/user.ts
- services/server/tests/api/user.test.ts
ClickUp Task: [https://app.clickup.com/t/86977xadu](https://app.clickup.com/t/86977xadu)
> added(server): endpoint to retrieve all tutors that a user has not started a chat with yet.

- packages/models/src/messages.ts
ClickUp Task: [https://app.clickup.com/t/86978y20k](https://app.clickup.com/t/86978y20k)
> modif(model): retrieving messages order has been reversed.

- packages/sol/src/availabilitySlots.ts
- packages/sol/src/index.ts
- packages/sol/tests/availabilitySlot.test.ts
- packages/sol/tests/rule.test.ts
- packages/sol/tests/time.test.ts
- packages/types/src/availabilitySlot.ts
ClickUp Task: [https://app.clickup.com/t/86978u2tr](https://app.clickup.com/t/86978u2tr)
> added(sol): availability slots required general logic

- .prettierignore
- packages/sol/src/session.ts
- packages/types/src/wss.ts
- services/server/fixtures/wss.ts
- services/server/src/lib/session.ts
- services/server/src/wss/handlers/connection.ts
- services/server/src/wss/handlers/session.ts
- services/server/tests/wss/session.test.ts
ClickUp Task: [https://app.clickup.com/t/86979r2et](https://app.clickup.com/t/86979r2et)
> feat: pre-join session wss event has been added. And session handler modified to utilize the acknowlegment mechanism.

- apps/nova/src/components/Chat/Messages.tsx
- packages/luna/src/components/Chat/ChatHeader/ChatHeader.tsx
ClickUp Task: https://app.clickup.com/t/86976zck8
> feat(nova): book lesson from chat page

- packages/atlas/src/chat.ts
- packages/models/fixtures/db.ts
- packages/models/src/messages.ts
- packages/models/src/rooms.ts
- packages/models/tests/messages.test.ts
- packages/models/tests/rooms.test.ts
- packages/models/tests/tutors.test.ts
- services/server/fixtures/db.ts
- services/server/src/handlers/chat.ts
- services/server/src/handlers/interview.ts
- services/server/src/handlers/lesson.ts
- services/server/src/index.ts
- services/server/src/routes/chat.ts
- services/server/tests/api/chat.test.ts
- services/server/tests/api/lesson.test.ts
- services/server/tests/api/topic.test.ts
- services/server/tests/api/user.test.ts
- services/server/tests/wss/messages.test.ts
- services/server/tests/wss/typing.test.ts
ClickUp Task: [https://app.clickup.com/t/86979rd81](https://app.clickup.com/t/86979rd81)
> modif: createRoom api handler now accepts an optional message.

- packages/luna/package.json
- packages/luna/src/components/Chat/ChatSummary/ChatSummary.tsx
- packages/luna/src/components/Lessons/PastLessonsTable.tsx
- packages/luna/src/components/Lessons/UpcomingLessonsSummary.tsx
- packages/luna/src/components/TutorOverview/TutorOverview.stories.tsx
- packages/luna/src/components/TutorOverview/TutorOverview.tsx
- packages/luna/src/components/TutorOverview/index.ts
- packages/luna/src/locales/ar-eg.json
> feat(luna): render tutor overview

- apps/nova/src/components/Chat/Messages.tsx
- apps/nova/src/components/Settings/ProfileForm.tsx
- apps/nova/src/components/Settings/UploadPhoto.tsx
- packages/atlas/src/lib/assets.ts
- packages/headless/src/user.ts
- packages/luna/src/components/Chat/ChatMessageGroup/ChatMessageGroup.tsx
Clickup task: https://app.clickup.com/t/86978nuae
Also, I've noticed that the server store its files in `assets/uploads` so I reflected that in the `asFullAssetsUrl` implementation
> feat(nova): added photo upload to students only

- apps/nova/src/components/Chat/Messages.tsx
- apps/nova/src/components/Chat/RoomsContainer.tsx
- apps/nova/src/pages/Chat.tsx
- packages/headless/src/chat.ts
- packages/luna/src/components/Chat/ChatMessage/ChatMessage.tsx
- packages/luna/src/components/Chat/ChatMessageGroup/ChatMessageGroup.stories.tsx
- packages/luna/src/components/Chat/ChatMessageGroup/ChatMessageGroup.tsx
- packages/luna/src/lib/chat.ts
- packages/types/src/message.ts
- packages/types/src/wss.ts
- services/server/fixtures/wss.ts
- services/server/src/wss/handlers/message.ts
clickup task: https://app.clickup.com/t/86976zcue
I don't understand why there is a formatting error, i checked it locally:
> feat(headless): added optimistic updates to edit/delete messages

- apps/nova/src/components/Chat/Messages.tsx
- apps/nova/src/components/Chat/Rooms.tsx
- apps/nova/src/components/Chat/RoomsContainer.tsx
- apps/nova/src/components/Layout/Navbar.tsx
- apps/nova/src/components/Layout/Sidebar.tsx
- apps/nova/src/lib/room.test.ts
- apps/nova/src/lib/room.ts
- apps/nova/src/pages/Chat.tsx
- packages/headless/src/chat.ts
- packages/luna/src/components/Chat/ChatRoom/ChatRoom.tsx
- packages/luna/src/components/Chat/SendInput/SendInput.tsx
- packages/luna/src/components/Chat/UserTyping/UserTyping.stories.tsx
- packages/luna/src/components/Chat/UserTyping/UserTyping.tsx
- packages/luna/src/components/Chat/index.ts
- packages/luna/tailwind.config.js
- packages/models/src/rooms.ts
- packages/types/src/room.ts
- packages/types/src/wss.ts
- services/server/src/lib/chat.ts
click up task: https://app.clickup.com/t/86976z967
> feat(ui): implemented typing indicator and online/offline using wss

- apps/nova/src/pages/Schedule.tsx
- packages/luna/src/components/Calendar/v2/Calendar.stories.tsx
- packages/luna/src/components/Calendar/v2/Calendar.tsx
- packages/luna/src/components/Calendar/v2/Events/LessonSlot/LessonSlot.stories.tsx
- packages/luna/src/components/Calendar/v2/Events/LessonSlot/LessonSlot.tsx
- packages/luna/src/components/Calendar/v2/Events/index.ts
- packages/luna/src/components/Calendar/v2/WeekTable.tsx
- packages/luna/src/components/Calendar/v2/index.ts
ClickUp Task: [https://app.clickup.com/t/8697h0bv8](https://app.clickup.com/t/8697h0bv8)
> modif: calender HourView has been substituted by the LessonSlot.

- apps/nova/src/components/dashboard/TutorOverview.tsx
- packages/types/src/tutor.ts
- services/server/src/handlers/user.ts
- services/server/tests/api/user.test.ts
ClickUp Task: [https://app.clickup.com/t/8697k2w70](https://app.clickup.com/t/8697k2w70)
> modif(api/nova): personalized tutor stats payload; it now includes the total learning time.

- apps/nova/src/components/Common/PageTitle.tsx
- apps/nova/src/components/Layout/Sidebar.tsx
- apps/nova/src/components/Tutors/Content.tsx
- apps/nova/src/pages/Root.tsx
- packages/luna/src/components/TutorCard/TutorCard.stories.tsx
- packages/luna/src/components/TutorCard/TutorCard.tsx
ClickUp Task: [https://app.clickup.com/t/8697k25w6](https://app.clickup.com/t/8697k25w6)
> style: all-tutors page has been modified to suit mobiles layout.

- apps/nova/src/components/Common/PageContent.tsx
- apps/nova/src/components/Common/PageTitle.tsx
- apps/nova/src/components/Settings/ProfileForm.tsx
- apps/nova/src/components/Settings/TopicSelector.tsx
- apps/nova/src/components/Settings/UploadPhoto.tsx
- apps/nova/src/pages/Root.tsx
- apps/nova/src/pages/Settings.tsx
- packages/luna/src/components/MultiSelect/MultiSelect.tsx
- packages/luna/src/components/Switch/FullSwitch.tsx
- packages/luna/src/locales/ar-eg.json
> feat(nova): impl mobile design for settings page

- .gitignore
- services/server/.gitignore
- services/server/fixtures/mockApi.ts
- services/server/tests/handlers/topic.test.ts
- services/server/tests/mockApi/topic.test.ts
ClickUp Task: [https://app.clickup.com/t/8697nk33n](https://app.clickup.com/t/8697nk33n)
> added: mockApi component in server/fixtures; with the corresponding tests for topics api handlers.

- services/server/src/handlers/availabilitySlot.ts
- services/server/src/lib/availabilitySlot.ts
- services/server/tests/api/slot.test.ts
Updating slots in the availabilitySlot api handler`set` has been updated to get the associated subslots (lesson & interviews) cancelled if they are rendered out of scope after updating the slot dates (start & end).
ClickUp Task: [https://app.clickup.com/t/8697p0e5t](https://app.clickup.com/t/8697p0e5t)
> modif: update slots mechanism in slots set api hanlder.

- packages/luna/src/components/Dialog/Dialog.tsx
Clickup task: https://app.clickup.com/t/8697nz9bu
a very simple PR :)
> feat(luna): implemented close dialog when clicking outside

- apps/web/src/components/Tutors/Content.tsx
- apps/web/src/pages/Tutors.tsx
- packages/ui/src/locales/ar-eg.json
https://app.clickup.com/t/8697nzjhb
> feat(nova): render tutors loading and error states

- services/server/.env.example
- services/server/.env.test
- services/server/.env.test.ci
- services/server/src/constants.ts
- services/server/src/lib/s3.ts
[ClickUp Task](https://app.clickup.com/t/8697p327a)
> added: digital ocean spaces config in server s3 lib file.

- apps/dashboard/src/pages/Plans.tsx
- apps/web/src/components/Layout/Navbar.tsx
- apps/web/src/components/Plans/Content.tsx
- apps/web/src/main.tsx
- apps/web/src/pages/Plans.tsx
- packages/ui/src/components/PlanCard/PlanCard.stories.tsx
- packages/ui/src/components/PlanCard/PlanCard.tsx
https://app.clickup.com/t/8697p3ufm
> feat(nova): render plans page mobile design

- services/server/src/constants.ts
- services/server/src/workers/background.ts
- services/server/tests/handlers/topic.test.ts
---
[ClickUp](https://app.clickup.com/t/8697nv4ja)
> modif: auth email jwt expires time has been modified to 24 hours.

- apps/web/src/components/LessonSchedule/Header.tsx
- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/pages/LessonsSchedule.tsx
- packages/ui/src/components/Lessons/LessonCard.tsx
- packages/ui/tailwind.config.js
---
[ClickUp](https://app.clickup.com/t/8697p3v1z)
> feat(web): impl lessons schedule mobile design

- .github/workflows/pr-closed.yml
---
[ClickUp](https://app.clickup.com/t/8697tj30t)
> ci: deploy stating server on merging a pull request

- apps/web/src/pages/TutorProfile.tsx
- packages/ui/src/locales/ar-eg.json
[ClickUp](https://app.clickup.com/t/8697pte36)
> feat(nova): render tutor profile loading & error states

- apps/web/src/components/Chat/Messages.tsx
- apps/web/src/components/Lessons/BookLesson.tsx
- apps/web/src/components/Tutors/Content.tsx
- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/components/dashboard/PastLessons.tsx
- apps/web/src/pages/TutorProfile.tsx
- packages/models/src/availabilitySlots.ts
- packages/types/src/availabilitySlot.ts
- packages/ui/src/components/Lessons/BookLesson/BookLessonDialog.stories.tsx
- packages/ui/src/components/Lessons/BookLesson/BookLessonDialog.tsx
- packages/ui/src/components/Lessons/BookLesson/DateSelection.tsx
- packages/ui/src/components/Lessons/BookLesson/TimeSelection.tsx
- packages/utils/src/availabilitySlots.ts
- services/server/src/handlers/availabilitySlot.ts
- services/server/src/lib/session.ts
Clickup task: https://app.clickup.com/t/8697jmr7g
Modified the dialog but now we need to modify the backend logic of booking lessons.
> feat(nova): book lessons works with slots instead of rules

- apps/web/src/components/Layout/Sidebar.tsx
- apps/web/src/components/LessonSchedule/Header.tsx
- apps/web/src/components/TutorProfile/TutorTabs.tsx
- apps/web/src/components/TutorSettings/Tabs/index.tsx
- apps/web/src/pages/Login.tsx
- apps/web/src/types/common.ts
- apps/web/src/types/routes.ts
---
[ClickUp](https://app.clickup.com/t/8697tvx7u)
> feat(web): derive tab state from the url params

- pnpm-lock.yaml
- services/apollo/package.json
- services/server/package.json
> chore: remove env-cmd & build command

- packages/assets/assets/arrow-down.svg
- packages/ui/src/components/MultiSelect/MultiSelect.tsx
- packages/ui/src/components/Select/Select.tsx
- packages/ui/src/components/Select/SelectV2.stories.tsx
- packages/ui/src/components/Select/SelectV2.tsx
- packages/ui/src/components/Select/index.ts
- packages/ui/src/components/Select/types.ts
- packages/ui/tailwind.config.js
---
[ClickUp](https://app.clickup.com/t/8697uut8m)
> impl: new select (dropdown menu) component has been implemented.

- packages/models/src/lessons.ts
- packages/models/tests/lessons.test.ts
- packages/types/src/lesson.ts
- packages/types/src/wss.ts
- packages/utils/src/availabilitySlots.ts
- services/server/fixtures/mockApi.ts
- services/server/src/handlers/lesson.ts
- services/server/src/routes/lesson.ts
- services/server/tests/handlers/lesson.test.ts
---
[ClickUp](https://app.clickup.com/t/8697p5dfb)
> added(server): update lesson api hanlder along with unit tests.

- services/apollo/src/build.ts
- services/apollo/src/handler.ts
---
[ClickUp](https://app.clickup.com/t/8697vyzr9)
> feat(apollo): update api handler to accept multiple workspaces

- .github/workflows/staging.yml
- .github/workflows/ui-deploy.yml
- apps/blog/next-env.d.ts
- pnpm-lock.yaml
- services/apollo/config.example.json
- services/apollo/src/build.ts
- services/apollo/src/constants.ts
- services/apollo/src/handler.ts
- services/apollo/src/index.ts
- services/apollo/src/middlewares/error.ts
- services/apollo/src/types.ts
---
[ClickUp](https://app.clickup.com/t/8697vyzrm)
> feat(apollo): deploy to staging server on merging a pull request

- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/components/dashboard/PastLessons.tsx
- apps/web/src/hooks/chat.ts
- packages/ui/src/components/Lessons/LessonCard.tsx
---
[ClickUp](https://app.clickup.com/t/8697q9nka)
> feat(web): impl sending msg feat of upcoming lessons card

- apps/web/src/components/Plans/data.json
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/PlanCard/PlanCard.tsx
---
[ClickUp](https://app.clickup.com/t/8697vz128)
> feat(web): add v1.0 plans pricing

- packages/ui/src/components/RatingDialog/RatingDialog.tsx
- packages/ui/src/components/RatingStars/RatingStars.tsx
---
[ClickUp](https://app.clickup.com/t/8697xa9tz)
> impl(ui): rating dialog for mobile layouts.

- apps/web/src/components/CompleteProfile/Form.tsx
- packages/ui/src/locales/ar-eg.json
---
[ClickUp](https://app.clickup.com/t/8697xd74j)
> added(web): helper texts in complete profile form.

- apps/landing/components/Ellipse.tsx
- apps/landing/components/Hero.tsx
---
[ClickUp](https://app.clickup.com/t/8697z8ke7)
> feat(landing): create ellipse component

- packages/assets/assets/play.svg
- packages/ui/src/components/VideoPlayer/V2/PlayButton.tsx
- packages/ui/src/components/VideoPlayer/V2/VideoPlayer.stories.tsx
- packages/ui/src/components/VideoPlayer/V2/VideoPlayer.tsx
- packages/ui/tailwind.config.js
---
[ClickUp](https://app.clickup.com/t/8697zq21e)
> modif: PlayButton on VideoPlayer ui component.

- apps/web/src/lib/query.ts
- apps/web/src/pages/Lesson.tsx
- apps/web/src/pages/UpcomingLessons.tsx
---
[ClickUp](https://app.clickup.com/t/8697z3399)
> added(web): new constraint to show rate dialog when user leave a lesson.

- packages/ui/src/components/VideoPlayer/V2/VideoPlayer.tsx
- packages/ui/src/components/VideoPlayer/V2/VideoProgressbar.tsx
> fix(ui): fix video player progress bar

- packages/ui/src/components/ConfirmationDialog/ConfirmationDialog.tsx
---
[ClickUp](https://app.clickup.com/t/8697pgf7e)
> feat(ui): implemented responsive confirmation dialog

- packages/ui/src/components/Toast/Toast.stories.tsx
- packages/ui/src/components/Toast/Toast.tsx
- packages/ui/src/components/Toast/provider.tsx
---
[ClickUp](https://app.clickup.com/t/8697p0xx1)
> feat(ui): update toast layout

- apps/web/src/components/Layout/Navbar.tsx
- apps/web/src/components/Layout/Sidebar.tsx
- apps/web/src/pages/Root.tsx
- packages/ui/src/components/Lessons/EmptyLessons.tsx
---
[ClickUp](https://app.clickup.com/t/869840ad3)
> feat(web): impl tablet sidebar

- apps/web/src/components/Layout/Sidebar.tsx
- apps/web/src/pages/Root.tsx
---
[ClickUp](https://app.clickup.com/t/86982n3cw)
> fix(web): make sidebar scrollabe

- apps/landing/components/Ellipse.tsx
- apps/landing/components/Hero.tsx
- apps/landing/components/Layout/Layout.tsx
- apps/landing/components/Layout/Sidebar.tsx
- packages/ui/tailwind.config.js
> fix(landing): fix landing sidebar not shown on tablet layout

- .gitignore
- eslint.config.mjs
- packages/radio/package.json
- packages/radio/src/index.ts
- packages/radio/src/whatsapp/index.ts
- packages/radio/src/whatsapp/store/file.ts
- packages/radio/src/whatsapp/store/index.ts
- packages/radio/src/whatsapp/store/memory.ts
- packages/radio/src/whatsapp/store/types.ts
- pnpm-lock.yaml
---
[ClickUp](https://app.clickup.com/t/86984pqjg)
> feat(radio): integrate whatsapp

- package.json
- packages/atlas/src/user.ts
- packages/models/fixtures/db.ts
- packages/models/src/tutors.ts
- packages/models/tests/tutors.test.ts
- packages/types/src/tutor.ts
- services/server/fixtures/db.ts
- services/server/src/handlers/user.ts
- services/server/src/lib/user.ts
- services/server/src/routes/user.ts
- services/server/tests/handlers/user.test.ts
---
[ClickUp](https://app.clickup.com/t/86982fr77)
> impl(server): get studio tutors endpoint.

- apps/web/src/components/Lessons/ManageLesson.tsx
- packages/assets/assets/LongLeftArrow.svg
- packages/assets/assets/LongRightArrow.svg
- packages/assets/assets/timer.svg
- packages/ui/src/components/Lessons/ManageLesson/Confirmation.tsx
- packages/ui/src/components/Lessons/ManageLesson/DateSelection.tsx
- packages/ui/src/components/Lessons/ManageLesson/DurationSelection.tsx
- packages/ui/src/components/Lessons/ManageLesson/ManageLessonDialog.stories.tsx
- packages/ui/src/components/Lessons/ManageLesson/ManageLessonDialog.tsx
- packages/ui/src/components/Lessons/ManageLesson/Stepper.tsx
- packages/ui/src/components/Lessons/ManageLesson/TimeSelection.tsx
- packages/ui/src/locales/ar-eg.json
---
[ClickUp](https://app.clickup.com/t/8697tgxu9)
> feat(ui): impl manage lessons dialog small screens design

- apps/landing/components/Tutors/TutorCard.tsx
- packages/ui/tailwind.config.js
---
[ClickUp](https://app.clickup.com/t/86988cqyh)
> fix(landing): refactor tutor card

- apps/web/src/App.tsx
- apps/web/src/components/Layout/Navbar.tsx
- apps/web/src/components/TutorProfile/Ratings.tsx
- apps/web/src/pages/Login.tsx
- apps/web/src/pages/Root.tsx
- apps/web/src/pages/TutorProfile.tsx
- packages/utils/src/routes/core.ts
---
[ClickUp](https://app.clickup.com/t/86989674v)
> feat(web): extend navbar with login & regiter when no user

- packages/ui/src/components/Accordion/Accordion.tsx
---
[ClickUp](https://app.clickup.com/t/8698b9qj6)
> fix(landing): update faq accordion

- services/server/src/validation/utils.ts
---
[ClickUp](#task-link-here)
> fix: get interview/list handler minor bug in zod config has been fixed

- apps/web/src/components/Lessons/ManageLesson.tsx
---
[ClickUp](https://app.clickup.com/t/8698dju4k)
> fix(web): fixed manage lesson dialog

- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/pages/LessonsSchedule.tsx
- package.json
- packages/ui/src/components/Lessons/EmptyLessons.tsx
- packages/ui/src/locales/ar-eg.json
---
[ClickUp](https://app.clickup.com/t/8698e8gf6)
> fix(web): student can book future slots only

- services/messenger/src/config.ts
- services/messenger/src/handlers/telegram.ts
- services/messenger/src/handlers/whatsapp.ts
- services/messenger/src/index.ts
---
[ClickUp](https://app.clickup.com/t/8698ecpap)
> feat(messenger): add flag to enable/disable whatsapp or telegram

- packages/models/scripts/seed.ts
---
[ClickUp](https://app.clickup.com/t/8698ecbdu)
> add(model): real phone numbers in seed data.

- packages/models/migrations/1742803643755_ext-users-table.ts
- packages/models/src/tutors.ts
- packages/models/src/users.ts
- packages/types/src/user.ts
- services/server/src/handlers/user.ts
---
[ClickUp](https://app.clickup.com/t/8698ecn2e)
> add(model): users table has been extended with two columns: enabled_whatsapp and enabled_telegram.

- packages/emails/emailer.ts
---
[ClickUp](https://app.clickup.com/t/8698fjh8j)
> feat(email): added email display name

- services/echo/handlers/func.go
- services/echo/public/demo.html
Sending and receiving a sound track along with the video track  has been tested in the demo, and seems to be working well with the current server implementation.
> feat(echo): sending sound tracks has been tested.

- packages/ui/src/components/Chat/ChatSummary/ChatSummary.stories.tsx
- packages/ui/src/components/Chat/ChatSummary/ChatSummary.tsx
---
[ClickUp](#task-link-here)
> fix(web): clamp long messages in chat summary

- .github/dependabot.yml
- apps/dashboard/src/lib/env.ts
- apps/dashboard/src/lib/route.ts
- apps/dashboard/src/pages/Login.tsx
- apps/dashboard/src/pages/Root.tsx
- apps/web/src/hooks/google.ts
- apps/web/src/pages/Login.tsx
- apps/web/src/pages/Root.tsx
- package.json
---
[ClickUp](https://app.clickup.com/t/8698mdhz3)
> fix(web): redirect users from web page

- packages/assets/scripts/types.ts
Credits go to @mostafakamar2308 and @neuodev, for inspecting and solving this error.
> fix: building assets package in windows os

- services/echo/handlers/func.go
- services/echo/handlers/ws.go
- services/echo/lib/record/record.go
- services/echo/lib/state/datachannel.container.go
- services/echo/lib/state/peer.container.go
- services/echo/lib/state/state.go
- services/echo/lib/utils/threads.go
- tmp/build-errors.log
Fixed issues related to integrating recording with streaming itself by @mmoehabb  mainly and @mostafakamar2308
> fix(echo): minor fixes in echo

- README.md
- packages/atlas/src/api/confirmationCode.ts
- packages/types/src/confirmationCode.ts
- services/server/bruno/confrimation-codes/send-verify-phone-code.bru
- services/server/bruno/confrimation-codes/verify-phone-code.bru
- services/server/src/handlers/confirmationCode.ts
- services/server/src/handlers/fawry.ts
- services/server/src/routes/confirmationCode.ts
- services/server/tests/handlers/confirmationCode.test.ts
---
[ClickUp](https://app.clickup.com/t/8698u1da8)
> feat(api): change notification method handler to verify phone

- packages/ui/package.json
- packages/ui/src/components/Tabs/Tabs.stories.tsx
- packages/ui/src/components/Tabs/Tabs.tsx
- packages/ui/src/components/Tabs/index.ts
- packages/ui/src/index.ts
---
[ClickUp](https://app.clickup.com/t/8698t21fg)
> feat(ui): impl tabs component

- packages/assets/assets/logo-v2.svg
- packages/assets/package.json
- packages/ui/src/components/Avatar/AvatarV2.stories.tsx
- packages/ui/src/components/Avatar/AvatarV2.tsx
> feat(ui): impl. avatar v2

- apps/web/src/main.tsx
- apps/web/src/pages/Root.tsx
- packages/atlas/src/api/index.ts
- packages/atlas/src/api/subscription.ts
- packages/headless/package.json
- packages/headless/src/constants/query.ts
- packages/headless/src/server/context.ts
- packages/headless/src/server/provider.tsx
- packages/headless/src/subscription.ts
- packages/headless/src/subscription/context.ts
- packages/headless/src/subscription/index.ts
- packages/headless/src/subscription/provider.tsx
- packages/models/scripts/seed.ts
- services/server/src/routes/subscription.ts
---
[ClickUp](https://app.clickup.com/t/8698vw67w)
> impl(web): subscription provider to be used within the frontend code.

- apps/dashboard/src/components/UserDetails/Content.tsx
- packages/models/migrations/1746623650880_drop-activated-by.ts
- packages/models/scripts/seed.ts
- packages/models/src/tutors.ts
- packages/models/tests/tutors.test.ts
- packages/types/src/tutor.ts
- packages/types/src/user.ts
- packages/ui/src/locales/ar-eg.json
- packages/utils/src/tutor.ts
- packages/utils/src/utils.ts
- services/server/fixtures/db.ts
- services/server/src/handlers/user.ts
- services/server/src/lib/tutor.ts
- services/server/tests/handlers/user.test.ts
- services/server/tests/workers/cache.test.ts
---
[ClickUp](https://app.clickup.com/t/8698wxq0x)
> feat: implemented activate/deactivate user through update endpoint

- packages/types/src/tutor.ts
- services/server/src/handlers/user.ts
The pagination was missing in the findFullTutors api handler.
> fix(server): pagination implemented in find-full-tutors api handler.

- apps/landing/components/Tutors.tsx
- packages/types/src/shortUrl.ts
- services/server/src/index.ts
- [ClickUp](https://app.clickup.com/t/8699e7xb4)
> fix: fixed missing shortUrl File

- packages/models/migrations/1750042958266_reports-fix.ts
- [ClickUp](https://app.clickup.com/t/8699eeejf)
> feat(models): fixed issue with reports table

- apps/dashboard/src/components/Tutors/Content.tsx
- apps/web/src/pages/Root.tsx
- packages/models/migrations/1749945965491_bypass-onboarding.ts
- packages/models/src/tutors.ts
- packages/models/tests/tutors.test.ts
- packages/types/src/tutor.ts
- packages/types/src/user.ts
- packages/ui/src/locales/ar-eg.json
- services/server/src/handlers/user.ts
- services/server/tests/handlers/user.test.ts
- [ClickUp](https://app.clickup.com/t/8699c774h)
This PR addresses an in-advance problem that will happen after deploying the new on-boarding flow; the tutors who have passed the previous manual on-boarding flow should not carry the burden to pass the new one. And accordingly, the following have been applied:
- packages/model
- `bypass_onboarding` column has been added to the tutors table.
- the tutors model script has been modified accordingly.
- services/server
- the users API update handler has been modified in order to allow admins to update the new column value.
- packages/type
- tutor types has been modified accordingly. and users type as well (UpdateApiPayload).
- apps/dashboard
- new column view has been added for admins in order to switch the bypass_onboarding value on and off.
- …
> feat: tutor bypass_onboarding flag has been implemented.

- apps/web/cypress.config.ts
- apps/web/cypress/e2e/login.cy.ts
- apps/web/cypress/e2e/register.cy.ts
- apps/web/cypress/lib/router.ts
- apps/web/cypress/lib/routes.ts
- apps/web/cypress/support/commands.ts
- apps/web/package.json
- packages/tests/package.json
- packages/tests/src/index.ts
- packages/ui/src/components/Input/Input.tsx
- pnpm-lock.yaml
- services/jobs/README.md
- [ClickUp](https://app.clickup.com/t/8699695c9)
> test(web): add e2e login and register tests

- packages/atlas/src/api/user.ts
- packages/headless/src/lessons.ts
- packages/models/src/lessons.ts
- packages/types/src/lesson.ts
- packages/types/src/tutor.ts
- services/server/src/handlers/user.ts
- services/server/src/lib/tutor.ts
- services/server/src/routes/user.ts
- services/server/tests/handlers/user.test.ts
- [ClickUp](https://app.clickup.com/t/86998mh1t)
- Context Video -> Sent in Telegram
> feat(server): impl tutoring minutes aggregation endpoint

- .github/pull_request_template.md
- packages/atlas/src/api/lesson.ts
- packages/types/src/lesson.ts
- services/server/fixtures/db.ts
- services/server/src/handlers/lesson.ts
- services/server/src/lib/lesson.ts
- services/server/src/routes/lesson.ts
- services/server/src/types/lesson.ts
- services/server/tests/handlers/lesson.test.ts
---
[ClickUp](https://app.clickup.com/t/86998hyd7)
> add(api): an endpoint for getting attened lessons stats has been implemented.

- packages/models/fixtures/db.ts
- packages/models/migrations/1749894349942_intro-video.ts
- packages/models/scripts/seed.ts
- packages/models/src/confirmationCodes.ts
- packages/models/src/index.ts
- packages/models/src/introVideos.ts
- packages/models/src/users.ts
- packages/models/tests/interviews.test.ts
- packages/models/tests/introVideos.test.ts
- packages/types/src/confirmationCode.ts
- packages/types/src/index.ts
- packages/types/src/introVideo.ts
- packages/types/src/user.ts
- services/server/src/handlers/user.ts
- [ClickUp](https://app.clickup.com/t/86999g1zd)
- [Context Video](https://drive.google.com/file/d/19gazCTIvH8ddYakmHPxBAHA672sUpva3/view?usp=drive_link)
> feat(models): implemented intro-video table

- apps/web/src/components/TutorProfileSettings/Content.tsx
> update(web): update inputs alignment in row

- packages/emails/components/Tailwind.tsx
- packages/emails/lib/assets.ts
- [ClickUp](https://app.clickup.com/t/8699kf8cr)
> update(emails): update logo with new one

- apps/landing/app/page.tsx
- apps/landing/components/Common/LottieAnimate.tsx
> fix: fixed lp

- .github/pull_request_template.md
- packages/atlas/src/api/introVideo.ts
- packages/models/package.json
- packages/models/src/tutors.ts
- packages/models/tests/tutors.test.ts
- packages/types/src/api.ts
- packages/types/src/introVideo.ts
- packages/ui/src/constants/error.ts
- packages/ui/src/locales/ar-eg.json
- services/server/fixtures/db.ts
- services/server/fixtures/file.ts
- services/server/src/constants.ts
- services/server/src/handlers/introVideo.ts
- services/server/src/index.ts
- services/server/src/lib/error.ts
- services/server/src/lib/introVideo.ts
- services/server/src/routes/index.ts
- services/server/src/routes/introVideo.ts
- services/server/tests/handlers/introVideo.test.ts
- services/server/tests/handlers/invoice.test.ts
- [ClickUp](https://app.clickup.com/t/86999g2xd)
- [Context Video](https://drive.google.com/file/d/18Vhxf1CoTlFJCOW3dQ1LDK0FXvx0URvC/view?usp=sharing)
> add(api): create handler for IntroVideos with corresponding unit tests.

- packages/models/jest.config.ts
- packages/models/src/lessons.ts
- packages/models/tests/lessons.test.ts
- packages/models/tests/rooms.test.ts
- services/jobs/.env.example
- services/jobs/src/index.ts
- services/jobs/src/jobs/backup.ts
- [ClickUp](https://app.clickup.com/t/8699eefj3)
> test(pkgs): add lesssons unit test

- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/pages/LessonsSchedule.tsx
- apps/web/src/pages/UpcomingLessons.tsx
- packages/models/scripts/seed.ts
- packages/models/src/demoSessions.ts
- packages/models/src/index.ts
- packages/tests/src/db.ts
- packages/types/src/api.ts
- packages/ui/src/components/Calendar/WeekTable.tsx
- packages/ui/src/components/Lessons/LessonCard.tsx
- packages/ui/src/constants/error.ts
- packages/ui/src/locales/ar-eg.json
- packages/utils/src/tutor.ts
- services/server/src/handlers/lesson.ts
- services/server/src/handlers/rating.ts
- services/server/src/handlers/topic.ts
- services/server/src/handlers/user.ts
- services/server/src/lib/error.ts
- services/server/tests/handlers/interview.test.ts
- services/server/tests/handlers/lesson.test.ts
- services/server/tests/handlers/rating.test.ts
Some bugs have been fixed and enhancements have been applied in this PR:
- Onboarding tutors in seeding data.
- LessonSchedule component bugs have been fixed (web app).
- Server lesson cancel API handler bug fixed.
- Updating the cache on each topic update.
- Rendering lessons on the calendar bug has been fixed.
> fix: some quirk bugs in the web app have been fixed.

- apps/web/src/components/Layout/Navbar.tsx
- apps/web/src/pages/Chat.tsx
- packages/types/src/api.ts
- packages/ui/src/components/Chat/EditMessage/EditMessage.tsx
- packages/ui/src/components/Loading/LoadingError.tsx
- packages/ui/src/constants/error.ts
- packages/ui/src/hooks/chat.ts
- packages/ui/src/locales/ar-eg.json
- services/server/src/handlers/chat.ts
- services/server/src/lib/error.ts
- [ClickUp](https://app.clickup.com/t/8699r4aeu)
> [!IMPORTANT]
> fix: issue with chat showing other users rooms

- packages/models/tests/cache/tutor.test.ts
- packages/types/src/tutor.ts
- services/server/fixtures/db.ts
- services/server/src/handlers/user.ts
- services/server/src/lib/subscription.ts
- services/server/src/lib/tutor.ts
- services/server/tests/handlers/user.test.ts
---
[ClickUp](https://app.clickup.com/t/86994vq18)
> modif(api): findOnboardedTutors handler has been modified to list tutors according to users subscription state.

- apps/landing/components/Tutors/Content.tsx
The free badge now rendered according to the type of the tutor.
> minor: modification in the landing page tutor-card.

- packages/models/scripts/seed.ts
- packages/models/src/tutors.ts
- packages/types/src/demoSession.ts
- services/server/fixtures/db.ts
- services/server/tests/handlers/demoSession.test.ts
- services/server/tests/handlers/interview.test.ts
- services/server/tests/handlers/introVideo.test.ts
- [Task Link](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/cynnzmu76xj8kbnsd3fkyd4gxja)
Notice a new pattern/convention has been used in testing.
> [!IMPORTANT]
> test: demo-session update api handler unit tests.

- services/server/fixtures/db.ts
- services/server/tests/handlers/demoSession.test.ts
- [Task Link](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/c5h7j7uixn7ytfnduzqz7nbebge)
> [!IMPORTANT]
> test: demo-session create api handler.

- packages/models/fixtures/db.ts
- packages/models/src/demoSessions.ts
- packages/models/tests/demoSessions.test.ts
- packages/types/src/session.ts
- services/server/src/handlers/demoSession.ts
- services/server/src/lib/session.ts
- services/server/tests/handlers/demoSession.test.ts
> impl: demo-session model has been finalized.

- packages/models/src/demoSessions.ts
- packages/types/src/demoSession.ts
- services/server/src/handlers/demoSession.ts
- services/server/tests/handlers/demoSession.test.ts
- [Task Link](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/c6ajkq4e31bggzdmyzaa81o97yo)
> [!IMPORTANT]
> impl(api): demo-session find api handler has been implemented.

- packages/atlas/src/api/subscription.ts
- packages/models/fixtures/db.ts
- packages/models/migrations/1748156775011_terminated-by-subscription.ts
- packages/models/package.json
- packages/models/src/subscriptions.ts
- packages/models/tests/plans.test.ts
- packages/types/src/api.ts
- packages/types/src/fawry.ts
- packages/types/src/subscription.ts
- packages/ui/src/constants/error.ts
- packages/ui/src/locales/ar-eg.json
- services/server/fixtures/fawry.ts
- services/server/jest.config.js
- services/server/src/fawry/lib/signature.ts
- services/server/src/handlers/fawry.ts
- services/server/src/handlers/subscription.ts
- services/server/src/lib/error.ts
- services/server/src/routes/subscription.ts
- services/server/tests/handlers/subscription.test.ts
---
[ClickUp](https://app.clickup.com/t/86995bx4y)
> impl(api): cancel subscription handler has been fully implemented.

- apps/landing/components/Hero.tsx
- [ClickUp](#task-link-here)
> [!IMPORTANT]
> fix(landing): fix hero section

- apps/dashboard/src/components/Plans/List.tsx
- apps/dashboard/src/components/Tutors/Content.tsx
- packages/types/src/utils.ts
- packages/ui/src/components/Button/Button.tsx
- packages/ui/src/components/Switch/FullSwitch.stories.tsx
- packages/ui/src/components/Switch/Switch.stories.tsx
- packages/ui/src/components/Switch/Switch.tsx
- packages/ui/src/components/Table/Table.tsx
- [ClickUp](https://app.clickup.com/t/8699p8jkv)
> [!IMPORTANT]
> update(ui): upgrade switch component

- apps/web/src/components/Layout/Navbar.tsx
- apps/web/src/components/Tutors/Content.tsx
- apps/web/src/hooks/logger.ts
- apps/web/src/pages/Root.tsx
- packages/ui/src/locales/ar-eg.json
- packages/utils/src/constants.ts
- [Task](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/cjt4jcaw5qinsbfdtd68uua9niw)
> enhance(web): students onboarding on the application.

- apps/web/src/components/Tutors/TutorCard.tsx
- apps/web/src/components/UpcomingLessons/Content.tsx
- apps/web/src/hooks/notification.ts
- packages/assets/assets/check-circle-v2.svg
- packages/ui/src/components/Toast/Toast.stories.tsx
- packages/ui/src/components/Toast/Toast.tsx
- packages/ui/src/components/Toast/context.ts
- [ClickUp](#task-link-here)
> [!IMPORTANT]
> refactor(ui): reimplement toast component to match design

- apps/web/src/components/Tutors/Content.tsx
- [MatterMost](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/cc795gdtyztrije9ytx8n4qb9fa)
> [!IMPORTANT]
> fix(web): filter tutors with English info

- apps/dashboard/src/components/Users/List.tsx
- apps/dashboard/src/hooks/error.ts
- apps/dashboard/src/pages/Users.tsx
- packages/headless/src/auth.ts
- packages/ui/src/components/ActionsMenu/ActionsMenu.tsx
- packages/ui/src/components/FilterQuery/FilterQuery.tsx
- packages/ui/src/locales/ar-eg.json
- services/server/src/handlers/auth.ts
- services/server/src/routes/auth.ts
- [ClickUp](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/cntsutqooiida3mrqtu55wgmm9r)
> [!IMPORTANT]
> fix(dashboard): fixes in admin dashboard

- apps/web/src/hooks/calendar.ts
- apps/web/src/lib/schedule.ts
- apps/web/src/pages/ScheduleManagement.tsx
- packages/ui/src/components/Calendar/Calendar.tsx
- packages/ui/src/components/Calendar/WeekTable.tsx
- packages/ui/src/components/ManageSchedule/ManageSchedule.tsx
- packages/ui/src/components/ManageSchedule/SlotRow.tsx
- packages/ui/src/components/ManageSchedule/types.ts
- packages/ui/src/lib/schedule.ts
- packages/ui/src/locales/ar-eg.json
- services/server/src/handlers/user.ts
- services/server/src/index.ts
- [ClickUp](https://app.clickup.com/t/8699r4ahm)
- [Context Video](https://drive.google.com/file/d/1Sr0K8IkdeUDfiPYBm3xlwAAMYzfVlix3/view?usp=drive_link)
> [!IMPORTANT]
> fix: fixed issues with calendar

- .github/pull_request_template.md
- apps/web/src/components/VerifyPhoneDialog/VerifyPhoneDialog.tsx
- [ClickUp](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vdz59ijd6ptnupqck1rf8medh8e/c7byto6xd83gu9nadbc3p467dqc)
> [!IMPORTANT]
> update(web): impl responsive small screens

- packages/ui/src/components/Avatar/AvatarV2.tsx
> fix(ui): update Avatar UI after removal in student settings

- apps/web/src/components/Settings/TopicSelection.tsx
- apps/web/src/pages/StudentDashboard.tsx
- apps/web/src/pages/TutorProfileSettings.tsx
> fix(web): prevent empty state appearing before data

- packages/models/migrations/1755169467004_students.ts
- packages/types/src/index.ts
- packages/types/src/student.ts
- [MatterMost](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/cn7ipmx7d1bbmfmg13xfrn89g6c)
> [!IMPORTANT]
> add(db): create students table

- apps/web/src/components/Layout/Sidebar.tsx
> fix(web): hide promotion for subscribed students

- apps/web/src/components/Tutors/Content.tsx
- [MatterMost](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/c49ua6ao87tduxfg3f3nqquwkzr)
> [!IMPORTANT]
> fix(web): correct grid column count for tutor display

- apps/web/src/components/Plans/Selector.tsx
- packages/ui/src/components/Card/PlanCard/PlanCard.tsx
> fix(web) fix plans discount and price

- apps/web/src/components/Tutors/Content.tsx
- apps/web/src/components/Tutors/TutorCard.stories.tsx
- apps/web/src/components/Tutors/TutorCard.tsx
- Use about instead bio in tutor card 
- Removed isValidTutorBio check from `web/src/components/Tutors/Content.tsx`
> refactor(web): use about instead of bio in tutor card

- apps/web/src/components/Session/Session.tsx
- apps/web/src/components/Session/SessionTimer.tsx
- apps/web/src/components/Session/Stream.tsx
- apps/web/src/components/Session/VideoStreams.tsx
- apps/web/src/components/Session/index.tsx
- services/jobs/src/jobs/lesson.ts
- services/server/src/handlers/lesson.ts
- services/server/src/handlers/user.ts
- services/server/tests/handlers/user.test.ts
- [MatterMost](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/csobnknc3n7fuzqsqgjtmipggyc)
> [!IMPORTANT]
> impl(web): add session timer in lessons

- apps/web/src/components/Settings/NotificationSettings.tsx
- apps/web/src/components/Settings/UnverifiedPhoneFragment.tsx
- apps/web/src/components/StudentSettings/Content.tsx
- apps/web/src/components/TutorAccountSettings/Content.tsx
- packages/ui/src/locales/ar-eg.json
- services/server/src/handlers/user.ts
- [MatterMost](https://chat.litespace.org/boards/team/ceomprh4n7d55e7uwff9mothxo/biqy5qk4ystdgzd8eyzascyk9ky/vo9dfcwjy3b8g7dm4qs48n4qyta/csorkmg8y6td4pbjjxqibhertye)
> [!IMPORTANT]
> feat(web): notifications are enabled by default.

- apps/web/src/components/Lessons/ManageLesson.tsx
- packages/utils/src/subscription.ts
> fix: issue of showing only current week in the scheduling of lessons

- apps/web/src/components/Chat/Messages.tsx
- apps/web/src/components/Chat/Rooms.tsx
- apps/web/src/components/Chat/RoomsPanel.tsx
- apps/web/src/components/Session/Controllers.tsx
- apps/web/src/components/Session/InSession.tsx
- apps/web/src/pages/Chat.tsx
- packages/models/src/messages.ts
- packages/ui/src/components/Chat/ChatHeader/ChatHeader.tsx
- services/server/src/handlers/chat.ts
> update(web): update chat notification number design

- .github/pull_request_template.md
- apps/web/src/components/Session/Controllers.tsx
- apps/web/src/components/Session/InSession.tsx
- apps/web/src/components/Session/PreSession.tsx
Report tutor view now disappears whenever the tutor joins the lesson, while the student is in. And detecting devices optimized by passing it from `pre-session` to the `controllers` component.
> fix(lesson): report-tutor alert and detect devices output.

- apps/web/src/hooks/time.ts
- packages/headless/src/user/provider.tsx
Minor bug has been fixed in the user provider. Only refresh token if the user data exists.
> fix: users stuck in the login page.
